/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Steven
 */
public class frmMarcadores extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public frmMarcadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblE1_1 = new javax.swing.JLabel();
        lblE2_1 = new javax.swing.JLabel();
        lblE4_1 = new javax.swing.JLabel();
        lblE3_1 = new javax.swing.JLabel();
        txtE1vsE2_1 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblE2_2 = new javax.swing.JLabel();
        lblE3_2 = new javax.swing.JLabel();
        lblE1_2 = new javax.swing.JLabel();
        lblE4_2 = new javax.swing.JLabel();
        lblE2_3 = new javax.swing.JLabel();
        lblE4_3 = new javax.swing.JLabel();
        lblE1_3 = new javax.swing.JLabel();
        lblE3_3 = new javax.swing.JLabel();
        txtE3vsE4_1 = new javax.swing.JTextField();
        txtE1vsE4_1 = new javax.swing.JTextField();
        txtE2vsE3_1 = new javax.swing.JTextField();
        txtE2vsE4_1 = new javax.swing.JTextField();
        txtE1vsE3_1 = new javax.swing.JTextField();
        txtE1vsE3_2 = new javax.swing.JTextField();
        txtE2vsE4_2 = new javax.swing.JTextField();
        txtE1vsE4_2 = new javax.swing.JTextField();
        txtE2vsE3_2 = new javax.swing.JTextField();
        txtE3vsE4_2 = new javax.swing.JTextField();
        txtE1vsE2_2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Cuadrangular de futbol");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Marcadores");

        lblE1_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE1_1.setForeground(new java.awt.Color(153, 0, 51));
        lblE1_1.setText("Equipo 1:");

        lblE2_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE2_1.setForeground(new java.awt.Color(153, 0, 51));
        lblE2_1.setText("Equipo 2:");

        lblE4_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE4_1.setForeground(new java.awt.Color(153, 0, 51));
        lblE4_1.setText("Equipo 4:");

        lblE3_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE3_1.setForeground(new java.awt.Color(153, 0, 51));
        lblE3_1.setText("Equipo 3:");

        txtE1vsE2_1.setBackground(new java.awt.Color(255, 255, 255));
        txtE1vsE2_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE1vsE2_1.setForeground(new java.awt.Color(0, 0, 0));
        txtE1vsE2_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE1vsE2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1vsE2_1ActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Goles:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Goles:");

        lblE2_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE2_2.setForeground(new java.awt.Color(153, 0, 51));
        lblE2_2.setText("Equipo 2:");

        lblE3_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE3_2.setForeground(new java.awt.Color(153, 0, 51));
        lblE3_2.setText("Equipo 3:");

        lblE1_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE1_2.setForeground(new java.awt.Color(153, 0, 51));
        lblE1_2.setText("Equipo 1:");

        lblE4_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE4_2.setForeground(new java.awt.Color(153, 0, 51));
        lblE4_2.setText("Equipo 4:");

        lblE2_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE2_3.setForeground(new java.awt.Color(153, 0, 51));
        lblE2_3.setText("Equipo 2:");

        lblE4_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE4_3.setForeground(new java.awt.Color(153, 0, 51));
        lblE4_3.setText("Equipo 4:");

        lblE1_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE1_3.setForeground(new java.awt.Color(153, 0, 51));
        lblE1_3.setText("Equipo 1:");

        lblE3_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblE3_3.setForeground(new java.awt.Color(153, 0, 51));
        lblE3_3.setText("Equipo 3:");

        txtE3vsE4_1.setBackground(new java.awt.Color(255, 255, 255));
        txtE3vsE4_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE3vsE4_1.setForeground(new java.awt.Color(0, 0, 0));
        txtE3vsE4_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE3vsE4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE3vsE4_1ActionPerformed(evt);
            }
        });

        txtE1vsE4_1.setBackground(new java.awt.Color(255, 255, 255));
        txtE1vsE4_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE1vsE4_1.setForeground(new java.awt.Color(0, 0, 0));
        txtE1vsE4_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE1vsE4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1vsE4_1ActionPerformed(evt);
            }
        });

        txtE2vsE3_1.setBackground(new java.awt.Color(255, 255, 255));
        txtE2vsE3_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE2vsE3_1.setForeground(new java.awt.Color(0, 0, 0));
        txtE2vsE3_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE2vsE3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE2vsE3_1ActionPerformed(evt);
            }
        });

        txtE2vsE4_1.setBackground(new java.awt.Color(255, 255, 255));
        txtE2vsE4_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE2vsE4_1.setForeground(new java.awt.Color(0, 0, 0));
        txtE2vsE4_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE2vsE4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE2vsE4_1ActionPerformed(evt);
            }
        });

        txtE1vsE3_1.setBackground(new java.awt.Color(255, 255, 255));
        txtE1vsE3_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE1vsE3_1.setForeground(new java.awt.Color(0, 0, 0));
        txtE1vsE3_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE1vsE3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1vsE3_1ActionPerformed(evt);
            }
        });

        txtE1vsE3_2.setBackground(new java.awt.Color(255, 255, 255));
        txtE1vsE3_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE1vsE3_2.setForeground(new java.awt.Color(0, 0, 0));
        txtE1vsE3_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE1vsE3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1vsE3_2ActionPerformed(evt);
            }
        });

        txtE2vsE4_2.setBackground(new java.awt.Color(255, 255, 255));
        txtE2vsE4_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE2vsE4_2.setForeground(new java.awt.Color(0, 0, 0));
        txtE2vsE4_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE2vsE4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE2vsE4_2ActionPerformed(evt);
            }
        });

        txtE1vsE4_2.setBackground(new java.awt.Color(255, 255, 255));
        txtE1vsE4_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE1vsE4_2.setForeground(new java.awt.Color(0, 0, 0));
        txtE1vsE4_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE1vsE4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1vsE4_2ActionPerformed(evt);
            }
        });

        txtE2vsE3_2.setBackground(new java.awt.Color(255, 255, 255));
        txtE2vsE3_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE2vsE3_2.setForeground(new java.awt.Color(0, 0, 0));
        txtE2vsE3_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE2vsE3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE2vsE3_2ActionPerformed(evt);
            }
        });

        txtE3vsE4_2.setBackground(new java.awt.Color(255, 255, 255));
        txtE3vsE4_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE3vsE4_2.setForeground(new java.awt.Color(0, 0, 0));
        txtE3vsE4_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE3vsE4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE3vsE4_2ActionPerformed(evt);
            }
        });

        txtE1vsE2_2.setBackground(new java.awt.Color(255, 255, 255));
        txtE1vsE2_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtE1vsE2_2.setForeground(new java.awt.Color(0, 0, 0));
        txtE1vsE2_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtE1vsE2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1vsE2_2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("vs");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("vs");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("vs");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("vs");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("vs");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("vs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblE1_3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtE1vsE3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblE1_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtE1vsE4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblE3_1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtE3vsE4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblE2_3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtE2vsE4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblE2_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtE2vsE3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblE1_1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtE1vsE2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(11, 11, 11)))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblE4_1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblE3_2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblE4_2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblE4_3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblE3_3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblE2_1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtE1vsE3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtE2vsE4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtE1vsE4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtE2vsE3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtE3vsE4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtE1vsE2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addGap(114, 114, 114))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE1_1)
                    .addComponent(lblE2_1)
                    .addComponent(txtE1vsE2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE1vsE2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE3_1)
                    .addComponent(lblE4_1)
                    .addComponent(txtE3vsE4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE3vsE4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE2_2)
                    .addComponent(lblE3_2)
                    .addComponent(txtE2vsE3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE2vsE3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE1_2)
                    .addComponent(lblE4_2)
                    .addComponent(txtE1vsE4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE1vsE4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE2_3)
                    .addComponent(lblE4_3)
                    .addComponent(txtE2vsE4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE2vsE4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE1_3)
                    .addComponent(lblE3_3)
                    .addComponent(txtE1vsE3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE1vsE3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtE1vsE2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1vsE2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1vsE2_1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtE3vsE4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE3vsE4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE3vsE4_1ActionPerformed

    private void txtE1vsE4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1vsE4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1vsE4_1ActionPerformed

    private void txtE2vsE3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE2vsE3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE2vsE3_1ActionPerformed

    private void txtE2vsE4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE2vsE4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE2vsE4_1ActionPerformed

    private void txtE1vsE3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1vsE3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1vsE3_1ActionPerformed

    private void txtE1vsE3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1vsE3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1vsE3_2ActionPerformed

    private void txtE2vsE4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE2vsE4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE2vsE4_2ActionPerformed

    private void txtE1vsE4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1vsE4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1vsE4_2ActionPerformed

    private void txtE2vsE3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE2vsE3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE2vsE3_2ActionPerformed

    private void txtE3vsE4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE3vsE4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE3vsE4_2ActionPerformed

    private void txtE1vsE2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1vsE2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1vsE2_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMarcadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMarcadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMarcadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMarcadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMarcadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblE1_1;
    public javax.swing.JLabel lblE1_2;
    public javax.swing.JLabel lblE1_3;
    public javax.swing.JLabel lblE2_1;
    public javax.swing.JLabel lblE2_2;
    public javax.swing.JLabel lblE2_3;
    public javax.swing.JLabel lblE3_1;
    public javax.swing.JLabel lblE3_2;
    public javax.swing.JLabel lblE3_3;
    public javax.swing.JLabel lblE4_1;
    public javax.swing.JLabel lblE4_2;
    public javax.swing.JLabel lblE4_3;
    public javax.swing.JTextField txtE1vsE2_1;
    public javax.swing.JTextField txtE1vsE2_2;
    public javax.swing.JTextField txtE1vsE3_1;
    public javax.swing.JTextField txtE1vsE3_2;
    public javax.swing.JTextField txtE1vsE4_1;
    public javax.swing.JTextField txtE1vsE4_2;
    public javax.swing.JTextField txtE2vsE3_1;
    public javax.swing.JTextField txtE2vsE3_2;
    public javax.swing.JTextField txtE2vsE4_1;
    public javax.swing.JTextField txtE2vsE4_2;
    public javax.swing.JTextField txtE3vsE4_1;
    public javax.swing.JTextField txtE3vsE4_2;
    // End of variables declaration//GEN-END:variables
}
